language: python

python:
  - "3.6"
#install:
#  - pip install pytest-cov
#  - pip install python-coveralls
# Command to run tests  
script:
  #python3 -m pytest --cov=src tests/test_motor_controller.py
  python3 -m pytest --cov=src tests/test_motor_controller.py
#after_success:
#  - coveralls

